# Site settings
title: Nicehjia Blog
header-img: "img/post-bg-re-vs-ng2.jpg"
tagline: "cn"  
description: "进一步有进一步的欢喜"  
baseurl: ""
url: "https://nicehjia.me" 

# About/contact
owner: 
  name: " nicehjia "
  email: nicehjia@qq.com
  bio: "年轻小伙紫"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
#   ( maruku | rdiscount | kramdown | redcarpet )
markdown: kramdown
highlighter:  kramdown
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Analytics settings
# Baidu Analytics
ba_track_id: d746177aed4155e5d4a6302307cb7aa8
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: nicehjia.me


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "nicehjia"
      header-img: "img/semantic.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
